import type { Metadata } from 'next'
import Link from 'next/link'
import { ChefHat } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Terms of Service — Robot Food',
  description: 'Terms and conditions for using Robot Food, the AI-powered recipe assistant.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Nav */}
      <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-sm">
        <div className="mx-auto flex h-16 max-w-4xl items-center px-4">
          <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <ChefHat className="h-6 w-6 text-primary" />
            <span className="font-bold text-lg text-foreground">Robot Food</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-4 py-16">
        <div className="mb-10">
          <h1 className="text-4xl font-bold tracking-tight text-foreground text-balance mb-3">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground">Last updated: March 2026</p>
        </div>

        <div className="space-y-10 text-foreground">

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">The service</h2>
            <p className="text-muted-foreground">
              Robot Food provides AI-powered recipe suggestions based on the ingredients you provide. By creating an account and using Robot Food, you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">AI-generated content</h2>
            <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-6 space-y-3">
              <p className="text-foreground">
                Recipes generated by Robot Food are <strong>AI suggestions</strong> and may contain errors, omissions, or inaccuracies. Please always use your own judgment when preparing food.
              </p>
              <ul className="space-y-2 text-muted-foreground list-disc list-inside text-sm">
                <li>We are not responsible for dietary advice, allergy information, or food safety outcomes.</li>
                <li>Recipe results may vary based on ingredient quality, measurements, and cooking conditions.</li>
                <li>Consult a qualified nutritionist or medical professional for dietary needs or restrictions.</li>
                <li>Do not rely solely on AI-generated recipes for managing serious food allergies or health conditions.</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">Your account</h2>
            <ul className="space-y-2 text-muted-foreground list-disc list-inside">
              <li>You must provide accurate and complete information when creating your account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must be at least 13 years old to use Robot Food.</li>
              <li>You may delete your account at any time from your Settings page.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">Acceptable use</h2>
            <p className="text-muted-foreground mb-3">Robot Food is provided for personal use. You agree not to:</p>
            <ul className="space-y-2 text-muted-foreground list-disc list-inside">
              <li>Scrape, crawl, or automate requests to Robot Food in bulk.</li>
              <li>Use Robot Food to build a competing product or service.</li>
              <li>Attempt to reverse-engineer the application or its AI prompts.</li>
              <li>Share your account credentials with others.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">Intellectual property</h2>
            <ul className="space-y-2 text-muted-foreground list-disc list-inside">
              <li>AI-generated recipe suggestions are provided for your personal use. You may save, print, and cook from them freely.</li>
              <li>The Robot Food application interface, branding, and design are owned by Robot Food and may not be reproduced or redistributed.</li>
              <li>We do not claim ownership of ingredients or recipe concepts — these are generated by AI from publicly available culinary knowledge.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">No warranty</h2>
            <p className="text-muted-foreground">
              Robot Food is provided <strong className="text-foreground">&ldquo;as is&rdquo;</strong> without warranty of any kind, express or implied. We do not guarantee that the service will be uninterrupted, error-free, or that recipe suggestions will meet your expectations. We reserve the right to modify or discontinue the service at any time.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">Changes to these terms</h2>
            <p className="text-muted-foreground">
              We may update these terms from time to time. Continued use of Robot Food after changes are posted constitutes your acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">Contact</h2>
            <p className="text-muted-foreground">
              Questions about these terms? Email us at{' '}
              <a
                href="mailto:hello@robot-food.com"
                className="text-primary underline underline-offset-4 hover:opacity-80"
              >
                hello@robot-food.com
              </a>.
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-border py-8 text-center text-sm text-muted-foreground">
        <div className="flex items-center justify-center gap-4">
          <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
          <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
          <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
        </div>
      </footer>
    </div>
  )
}
